name: åŒæ­¥BoyceLig-Clashæ±‰åŒ–ä»“åº“
on:
  schedule:
    - cron: '30 */8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-BoyceLig-Clash_Chinese_Patch
   
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
      SERVERCHAN_SCKEY: true
      TZ: Asia/Shanghai
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: ç”µæŠ¥é€šçŸ¥
        if: env.SERVERCHAN_SCKEY == 'true'
        run: |
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=ğŸ‰ ä¸»äººï¼šå¼€å§‹ä¸ºæ‚¨åŒæ­¥BoyceLig-Clash_Chinese_Patchä»“åº“,è¯·è€å¿ƒç­‰å¾…...... ğŸ˜‹" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
       
      - name: sync BoyceLig-Clash_Chinese_Patch
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/BoyceLig/Clash_Chinese_Patch.git"
          source_branch: "main"
          destination_branch: "BoyceLig"
          github_token: ${{ secrets.PAT }}
          
      - name: ç”µæŠ¥é€šçŸ¥
        if: env.SERVERCHAN_SCKEY == 'true'
        run: |
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=æˆ‘äº²çˆ±çš„âœ¨ä¸»äººâœ¨ï¼šæ‚¨åŒæ­¥çš„BoyceLig-Clash_Chinese_Patchä»“åº“é¡ºåˆ©åŒæ­¥å®Œæˆäº†ï¼ğŸ’" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
