name: åŒæ­¥vooidzero-ä¸‹è½½Bç«™ è§†é¢‘/ç›´æ’­/æ¼«ç”»ä»“åº“
on:
  schedule:
    - cron: '5 10 */5 * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-vooidzero-B23Downloader
     
env:
  PAT: ${{ secrets.PAT }} 
  SERVERCHAN_SCKEY: true
  TZ: Asia/Shanghai  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: ç”µæŠ¥é€šçŸ¥
        if: env.SERVERCHAN_SCKEY == 'true'
        run: |
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=ğŸ‰ ä¸»äººï¼šå¼€å§‹ä¸ºæ‚¨åŒæ­¥vooidzero-B23Downloaderä»“åº“,è¯·è€å¿ƒç­‰å¾…...... ğŸ˜‹" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
       
      - name: sync vooidzero-B23Downloader
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/vooidzero/B23Downloader.git"
          source_branch: "main"
          destination_branch: "vooidzero"
          github_token: ${{ secrets.PAT }}
          
      - name: ç”µæŠ¥é€šçŸ¥
        if: env.SERVERCHAN_SCKEY == 'true'
        run: |
          curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=æˆ‘äº²çˆ±çš„âœ¨ä¸»äººâœ¨ï¼šæ‚¨åŒæ­¥çš„vooidzero-B23Downloaderä»“åº“é¡ºåˆ©åŒæ­¥å®Œæˆäº†ï¼ğŸ’" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
