name: åŒæ­¥whyour-qinglongä»“åº“
on:
  schedule:
    - cron: '30 */8 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-whyour-qinglong
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync whyour-qinglong
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/whyour/qinglong.git"
          source_branch: "develop"
          destination_branch: "whyour"
          github_token: ${{ secrets.PAT }}
          
          
    - name: ç”µæŠ¥é€šçŸ¥
      if: steps.organizer.outputs.status == 'success' && env.SERVERCHAN_SCKEY == 'true'
      run: |
        curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=æˆ‘äº²çˆ±çš„âœ¨ä¸»äººâœ¨ï¼šæ‚¨ä»“åº“é’é¾™å·²ç»é¡ºåˆ©ç¼–è¯‘å®Œæˆäº†ï¼ğŸ’" "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage"
